spring: 
  redis:
    host: redis地址
    port: 6379
    password: 你的密码
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 0
    timeout: 10000
    redisson:
      #配置文件目录
      config: classpath:singleServerConfig.yaml
