server:
  servlet:
    context-path: /auth
  port: 63070

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://数据库地址:3306/lg_user?serverTimezone=UTC&userUnicode=true&useSSL=false&
      username: root
      password: 你的密码
weixin:
  appid: 微信appid
  secret: 你的密钥
