spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://数据库地址:3306/lg_order?serverTimezone=UTC&userUnicode=true&useSSL=false
      username: root
      password: 你的密码

  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true 


pay:
  alipay:
    APP_ID: 支付宝app_id
    APP_PRIVATE_KEY: app私钥
    ALIPAY_PUBLIC_KEY: 支付宝公钥
  urlpattern: http://192.168.144.1/api/orders/open/requestpay?payNo=%s #支付宝扫码跳转地址