spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://数据库地址:3306/lg_system?serverTimezone=UTC&userUnicode=true&useSSL=false&
      username: root
      password: 你的密码