### 授权码模式
### 第一步申请授权码(浏览器请求)/oauth/authorize?client_id=LgWebApp&response_type=code&scope=all&redirect_uri=http://www.51xuecheng.cn
### 第二步申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=LgWebApp&client_secret=LgWebApp&grant_type=authorization_code&code=WnCHuO&redirect_uri=http://www.51xuecheng.cn


### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=LgWebApp&client_secret=LgWebApp&grant_type=password&username={"username":"stu1","password":"111111","checkcode":"6r5g","checkcodekey":"checkcode:a3184ed00eb84d7dbe544f5e3f463a07","authType":"password"}

### 校验令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsibGVhcm5pbmdkb2ciXSwidXNlcl9uYW1lIjoie1wiYmlydGhkYXlcIjpcIjIwMjItMDktMjhUMTk6Mjg6NDZcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MFwiLFwibmFtZVwiOlwi5a2m55SfMVwiLFwibmlja25hbWVcIjpcIuWkp-awtOeJm1wiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJzdHUxXCIsXCJ1c2VycGljXCI6XCJodHRwOi8vZmlsZS41MXh1ZWNoZW5nLmNuL2RkZGZcIixcInV0eXBlXCI6XCIxMDEwMDFcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjg2Mjg0NTE2LCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiI3ZDdmNTQzYy04Mjk1LTQ1NmMtYjNiZC1mYmYzYjhkM2M5ZDkiLCJjbGllbnRfaWQiOiJMZ1dlYkFwcCJ9.nKYmK86TQaji-vZzJHsXj0z1-cLmcFYPkBDmRBtwT8g

### 未携带token访问资源服务
GET {{content_host}}/content/course/2

### 携带token访问资源服务
GET {{content_host}}/content/course/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsibGVhcm5pbmdkb2ciXSwidXNlcl9uYW1lIjoibGlzaSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODYyMTIxMjIsImF1dGhvcml0aWVzIjpbInAyIl0sImp0aSI6IjgwODgwMjJkLTAwZjYtNDZmMi04ODU1LTRmNzU3YzYyOTQ1NyIsImNsaWVudF9pZCI6IkxnV2ViQXBwIn0.zfMorAPgbqhYGgh3iU7rB7uRdUkFgxzUJTKKDWhNsno


### 通过网关访问资源服务
GET {{gateway_host}}/content/course/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsibGVhcm5pbmdkb2ciXSwidXNlcl9uYW1lIjoie1wiYmlydGhkYXlcIjpcIjIwMjItMDktMjhUMTk6Mjg6NDZcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MFwiLFwibmFtZVwiOlwi5a2m55SfMVwiLFwibmlja25hbWVcIjpcIuWkp-awtOeJm1wiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJzdHUxXCIsXCJ1c2VycGljXCI6XCJodHRwOi8vZmlsZS41MXh1ZWNoZW5nLmNuL2RkZGZcIixcInV0eXBlXCI6XCIxMDEwMDFcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjg2MjMxNTM1LCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiJlNjFlMTNhMy0wYTMwLTQ5ODktODk5MC1iYjI0MDQyNzVkZjQiLCJjbGllbnRfaWQiOiJMZ1dlYkFwcCJ9.l3wIotGZl5V8SfD-NUzL_4kO7hCJgdmENnHC37TwVmg